services:
  web:
    build: ./web
    ports:
      - "8000:80"
    volumes:
      - ./web:/app
      - ./db:/db
    depends_on:
      - db
    container_name: conectati_web 

  db:
    build: ./db
    volumes:
      - ./db:/db
    container_name: conectati_db

