# Generated by Django 5.2.4 on 2025-08-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('ci', models.TextField(unique=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color_favorito', models.TextField(blank=True, null=True)),
                ('libro_favorito', models.TextField(blank=True, null=True)),
                ('musica_favorita', models.TextField(blank=True, null=True)),
                ('videojuegos', models.TextField(blank=True, null=True)),
                ('lenguajes', models.TextField(blank=True, null=True)),
                ('contrasena', models.TextField()),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('archivo_nombre', models.TextField(blank=True, null=True)),
                ('privacidad', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estrellas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Publicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(blank=True, default=False, null=True)),
                ('por_correo', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('publicacion_id', models.IntegerField(blank=True, null=True)),
                ('comentario_id', models.IntegerField(blank=True, null=True)),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_emitidas', to='app.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chat')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Mensaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(blank=True, null=True)),
                ('idioma', models.TextField(blank=True, null=True)),
                ('publicaciones_privadas', models.BooleanField(blank=True, null=True)),
                ('notificar_chat', models.BooleanField(blank=True, null=True)),
                ('notificar_comentario', models.BooleanField(blank=True, null=True)),
                ('notificar_amistad', models.BooleanField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Configuracion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('respuesta_a', models.ForeignKey(blank=True, db_column='respuesta_a', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comentario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Comentario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'CodigoRecuperacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usuario2_set', to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistad_para_usuario_set', to='app.usuario')),
            ],
            options={
                'db_table': 'Amistad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptada', models.DateTimeField(blank=True, null=True)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_chat_enviadas', to='app.usuario')),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_chat_recibidas', to='app.usuario')),
            ],
            options={
                'db_table': 'SolicitudChat',
                'managed': True,
                'unique_together': {('de_usuario', 'para_usuario')},
            },
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'Estrella',
                'managed': True,
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
