"""
Django settings for project_conectati project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o76^a6f3gapu@vvl=2*6pw2-cz%3!4c#$gds+a*l=r509m81ww'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_conectati.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.usuario_actual',
                'app.context_processors.datos_chat_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_conectati.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


BASE_DIR = Path(__file__).resolve().parent.parent.parent  # <- subimos hasta la raíz del proyecto

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'web' / 'db.sqlite3',
        #'NAME': '/app/db.sqlite3', # <- ruta de la base de datos cuando se usa Docker
    },
    'conectati': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': '/app/db/ConectATI_db.db', # <- ruta de la base de datos cuando se usa Docker
        'NAME': BASE_DIR / 'web' / 'db' / 'ConectATI_db.db', # <- ruta de la base de datos cuando se usa python manage.py runserver
    }

}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True 
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path("/web/static")  # <- importante para que Django recoja ahí
STATICFILES_DIRS = [
    BASE_DIR / 'web' / 'app' / 'static',  # <- donde están tus CSS, imágenes, etc.
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATABASE_ROUTERS = ['db_router.ConectATIRouter']
APPEND_SLASH = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'web', 'media')

CSRF_TRUSTED_ORIGINS = ['http://localhost:8000']  # Ajusta según el dominio si estás en otro entorno

DEFAULT_CHARSET = 'utf-8'

# Configuración para envío de correos
# Para testing: usa console backend (muestra emails en consola)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# OPCIÓN 1: Gmail con contraseña de aplicación (REQUIERE 2FA)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'conectatiUCV@gmail.com'
EMAIL_HOST_PASSWORD = 'itjb jqpd ibfp pfkw'  # ← Contraseña de aplicación (NO la normal)
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 60

# Para volver a testing en consola:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
