name: Django Tests CI

on:
  push:
    branches: [ reto19 ]
  pull_request:
    branches: [ reto19 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        working-directory: web
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        working-directory: web
        run: |
          python manage.py test app.tests.test_register
          python manage.py test app.tests.test_login
